on:
  push:
    branches:
      - develop

permissions:
  contents: write
  actions: write

# There should only be one instance of this
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

name: Deploy snapshot builds
jobs:
  deploy-release-snapshot:
    container:
      image: cimg/android:2025.03.1-node
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Setup build environment
      uses: https://git.private.coffee/kumi/Android-Password-Store/.github/reusable-workflows/setup-gradle@0d2013262f86df7710b5f3c362b28492499b3030
      with:
        fetch-depth: 0
        dependency-graph: generate-and-submit

    - name: Decrypt secrets
      shell: bash
      run: scripts/signing-setup.sh "$ENCRYPT_KEY"
      env:
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    - name: Build release app
      shell: bash
      run: ./gradlew collectFreeReleaseApks collectNonFreeReleaseApks bundleFreeRelease bundleNonFreeRelease -PsentryUploadMappings
      env:
        SNAPSHOT: "true"
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    - name: Clean secrets
      shell: bash
      run: scripts/signing-cleanup.sh

    - name: Deploy snapshot
      uses: https://code.forgejo.org/forgejo/upload-artifact@v4
      with:
        name: snapshot.zip
        path: app/outputs/