on:
  push:
    branches:
      - develop

permissions:
  contents: write
  actions: write

# There should only be one instance of this
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

name: Deploy snapshot builds
jobs:
  deploy-release-snapshot:
    runs-on: docker
    container:
      image: cimg/android:2025.12.1-node
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Decrypt secrets
      shell: bash
      run: scripts/signing-setup.sh "$ENCRYPT_KEY"
      env:
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    - name: Build release app
      shell: bash
      run: ./gradlew collectFreeReleaseApks collectNonFreeReleaseApks bundleFreeRelease bundleNonFreeRelease -PsentryUploadMappings
      env:
        SNAPSHOT: "true"
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    - name: Clean secrets
      shell: bash
      run: scripts/signing-cleanup.sh

    - name: Deploy snapshot
      uses: https://code.forgejo.org/forgejo/upload-artifact@cb8afe72b42edc798abfb8fcb556cf660d894245 # v5
      with:
        name: snapshot.zip
        path: app/build/outputs/