on:
  pull_request:
  merge_group:

name: Check pull request

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  SENTRY_DSN: 'https://public_key@example.com/project_id'

jobs:
  check-codestyle:
    runs-on: docker
    container:
      image: cimg/android:2025.12.1-node
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Check codestyle
        shell: bash
        run: ./gradlew spotlessCheck

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          name: Build report (check-codestyle)
          path: build/reports/kotlin-build/

  unit-tests:
    runs-on: docker
    container:
      image: cimg/android:2025.12.1-node
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run unit tests
        shell: bash
        run: ./gradlew test -PslimTests

      - name: (Fail-only) Upload test report
        if: "${{ failure() }}"
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          name: Test report (unit-tests)
          path: app/build/reports

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          name: Build report (unit-tests)
          path: build/reports/kotlin-build/

  build-apks:
    runs-on: docker
    container:
      image: cimg/android:2025.12.1-node
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build debug APKs
        shell: bash
        run: ./gradlew assembleFreeDebug assembleNonFreeDebug assembleNonFreeRelease

      - name: Upload built APKs
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          name: Built APKs
          path: app/build/outputs/

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          name: Build report (build-apks)
          path: build/reports/kotlin-build/

  check-api:
    runs-on: docker
    container:
      image: cimg/android:2025.12.1-node
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Check library API
        shell: bash
        run: ./gradlew metalavaCheckCompatibilityRelease

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          name: Build report (check-api)
          path: build/reports/kotlin-build/

  lint:
    runs-on: docker
    container:
      image: cimg/android:2025.12.1-node
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run Lint
        shell: bash
        run: ./gradlew lint

      - name: Upload Kotlin build report
        if: "${{ always() }}"
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          name: Build report (lint)
          path: build/reports/kotlin-build/
